# Generated by Django 4.1.7 on 2023-03-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=200, null=True),
        ),
    ]
